jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - script: |
        echo success in Windows!
      displayName: Run Tests


  - job: Linux

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          sudo apt-get install -y openmpi-bin
          sudo apt-get install -y libprotobuf-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler
          sudo apt-get install -y --no-install-recommends libboost-all-dev
          sudo apt-get install -y libatlas-base-dev
          sudo apt-get install -y libgflags-dev libgoogle-glog-dev
        displayName: Apt install dependencies
      - script: |
          echo success in linux!
        displayName: Run Tests


  - job: MacOS

    pool:
      vmImage: 'macOS-10.13'

    steps:
      - script: |
          echo success in linux!
        displayName: Run Tests